[package]
name = "cli-news"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "0.6.0"
crossterm = "0.22.1"
dotenv = "0.15.0"
hnapi = {path = "./hnapi"}
termimad = "0.19.4"

